### ISSUE TITLE
Show ID in conversation pulldown menu

### ISSUE THREAD

**Issue by marsch-** [krobelus/cyanide#1]
Hi,

thanks for the great app! Would be good to have the persons Tox ID - or better "Copy X's Tox ID" - in the respective conversations pulldown menu. This would make it quite easy to hand over IDs between friends without resorting to email etc.

Thanks.

**Comment by krobelus** [comment]
I'm working on this, but as pointed out in irungentoo/toxcore#1044 there is no guarantee that the friend didn't change the nospam value. It will also only work for friends added with Cyanide (as opposed to copying tox_save.tox)

Using a service like https://toxme.se or https://utox.org would also make this easier
