### ISSUE TITLE
Manage translations with Weblate (or similar)

### ISSUE THREAD

**Issue by ghost** [krobelus/cyanide#10]
It would be useful if the translations for this application could be managed with Weblate (https://hosted.weblate.org/), Transifex (https://www.transifex.com/) or something else that allows people to easily translate online.

**Comment by silverhook** [comment]
Personally I’m not very keen on web-based translating – dedicated programs like Lokalize are nicer to use – but for Cyanide it might be a good option, since I guess there will not be too many strings in Tox.

For so few strings it might make sense to have a low entry-barrier for potential translaters.

From the two, I would personally prefer Weblate (or Pootle), since they’re Free Software as well.

**Comment by silverhook** [comment]
There’s also [Zanata](http://zanata.org).

BTW, it is said that Jolla might set up a Pootle server soon™ – if that is the case, it might make sense to centralise all Sailfish/Mer/Nemo/apps translations on that one server.

**Comment by ghost** [comment]
Oh, that would be great if it's true. And I agree that Weblate, Pootle or Zanata would be the best options.

**Comment by krobelus** [comment]
I did apply for hosting at Weblate.

**Comment by eson57** [comment]
I just took a look at Weblate and, as always, the risk of bad translations is imminent. Do Weblate allow you to block a bad translator if necessary?
You wouldn't believe how many worthless Swedish software translations there is out there. Especially in the open source world, but also proprietary freeware.

**Comment by krobelus** [comment]
I looked through the [changelog](http://docs.weblate.org/en/latest/changes.html)
and found "Support for locking translation by translator." so it seems possible.
The biggest problem  is probably when there is a bad translation that no one is able to verify.
We'll see how it works out - if it's too bad we can always limit translations to patches/pr which seems to keep less dedicated translators out.

**Comment by eson57** [comment]
Ok, that's good enough for me.

**Comment by ghost** [comment]
@eson57: you can review others' translations and modify them anyway, so you'd probably only need to block someone if they're really submitting awful translations on purpose. I have generally good experiences with Weblate and Transifex, though. Besides, if someone wants to submit a bad translation, they can also do that here, and unless (other) speakers of the language notice, it's likely to get accepted just as much as any translation through a web service.

**Comment by eson57** [comment]
Well, I don't have all that good experiences, I've had more than one translation messed up by some guy that really shouldn't do Swedish translations, and for me it kind of take the fun out of translating, when I have to clean up someone else's mess.
Anyway, I'm okay with the current solution.

**Comment by silverhook** [comment]
On today’s [Mer Meeting](http://merproject.org/meetings/mer-meeting/2015/mer-meeting.2015-03-24-15.00.html) it was said that:

> Jolla is working on translation service (WIP, no ETA) that allows communtiy translation contributions. Should be feasible to use it for adding new projects (for 3rd party apps) to it.

and that 

> Tool of choice is Pootle […]

**Comment by krobelus** [comment]
Now cyanide is on weblate: https://hosted.weblate.org/projects/cyanide/
It seems to work :+1: .
I need to go over the translation strings though - some aren't even used or are error messages of errors that can never happen.
