### ISSUE TITLE
conversation page pulldown menu bug

### ISSUE THREAD

**Issue by mentaljam** [krobelus/cyanide#11]
Hi!
I noticed a bug in pulldown menu on conversation page. Page doesn't go down when menu is pulled, so menu overlaps page.
![screenshot-10-03-15-11-27-17](https://cloud.githubusercontent.com/assets/6236802/6571561/c8d629e2-c71a-11e4-89e0-62daabe3ff99.png)

**Comment by krobelus** [comment]
Fixed, thanks!
