### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by eson57** [krobelus/cyanide#2]
Hi,

First of all, thanks for giving us encrypted IM.
You can find Swedish translation at link below, if you want it. I will watch and update translation whenever needed.
https://svenskasprakfiler.se/tempfiles/cyanide-sv.ts

eson

**Comment by krobelus** [comment]
Thanks, added :)

**Comment by eson57** [comment]
Here's the latest update...
https://svenskasprakfiler.se/tempfiles/cyanide-sv.ts

**Comment by eson57** [comment]
Next update finished...
https://svenskasprakfiler.se/tempfiles/cyanide-sv.ts

**Comment by eson57** [comment]
And the next one...  
https://svenskasprakfiler.se/tempfiles/cyanide-sv.ts

**Comment by eson57** [comment]
next...
https://svenskasprakfiler.se/tempfiles/cyanide-sv.ts

**Comment by eson57** [comment]
Latest update uploaded...
https://svenskasprakfiler.se/tempfiles/cyanide-sv.ts

**Comment by eson57** [comment]
Update 2015-03-17
https://svenskasprakfiler.se/tempfiles/cyanide-sv.ts

**Comment by eson57** [comment]
Update 2015-03-20
https://svenskasprakfiler.se/tempfiles/cyanide-sv.ts
