### ISSUE TITLE
Feature Request: Chat logs

### ISSUE THREAD

**Issue by tlaerm** [krobelus/cyanide#22]
Hi Johannes, 

I would like to encourage you to include chat logs. It's the only thing seriously missing from the app. Keep up the great work.

Tom

**Comment by krobelus** [comment]
Hi, thanks for your feedback!
I will add chat logs soon.
I plan to use a new sqlite database per profile like qTox does, so this shouldn't be too hard

**Comment by krobelus** [comment]
done

**Comment by tlaerm** [comment]
Fanstastic! Just upgraded from Warehouse. New version looks great.
