### ISSUE TITLE
QR-Code goes

### ISSUE THREAD

**Issue by Nokius** [krobelus/cyanide#26]
Today I installed the update and I saw u added the QR-Code feature (Thanks for that!!). After I returned from Cover view to the Profile.qml the QR-Code was gone reopen the Profile returns it. It looks like that the QR-Code get flushed, when the Appliaction is minimized. I did saw anything in the logs (starting cyandige via cli)

**Comment by krobelus** [comment]
ah ok, it seems like i have to repaint the QRCode when Qt.application.active is changed
thanks ;)
