### ISSUE TITLE
Add to Tox wiki clients list

### ISSUE THREAD

**Issue by ghost** [krobelus/cyanide#27]
I think it would be a good idea to add cyanide to the list of Tox clients on the Tox wiki: https://wiki.tox.chat/users/clients

That way more people can find out about it or even help out with development.

**Comment by ghost** [comment]
Done.

**Comment by quatrox** [comment]
That link is no longer active and cyanide is no longer listed on tox.chat as far as I can tell.

**Comment by ghost** [comment]
They only keep clients with active development on the main page. The separate page for cyanide still exists: https://wiki.tox.chat/clients/cyanide
