### ISSUE TITLE
trouble to send or receive friend request

### ISSUE THREAD

**Issue by ghost** [krobelus/cyanide#39]
-i have cyanide in my 3 devices and can't sent o receive friends request in the all devices. in some case i receive the friend request  but when i open the request to accept .it is not permitted. 
cyanide===v0. 2.6
sailfishOS= 2.0.5.6

**Comment by krobelus** [comment]
Do you get any error message? The notifications currently don't pop up as they used to but they are shown in the notification area

**Comment by ghost** [comment]
- i don't get any error  message.
- i know on the new notifications area, but same trouble i don't get any notifications to accept.
- in rare case i get the notifications  but when open the notifications to accept. it is not permitted. ignore option is accepted, but to accept it is not permitted.  
- i tested with antox to cyanide or cyanide to antox.but same issue in both app. 
- *** I send friend request from cyanide to utox ,then i get the notification friend as well in utox i get connected. but send friend request from utox to cyanide i never get notification friend in cyanide,unable to connect. 
- *** Cyanide to cyanide unable to receive friend request . so the main problem is to receive the friend request in cyanide or there is still a problem with notifications 
- before you released v 0.2.6 i build cyanide from  github and everything ok with friend request ,but I had trouble listening to the other person with the call, the other person if he could hear me. To make the call or accept a call, everything is fine. The problem is that I can not hear the other call, so that could do another detail

**Comment by ghost** [comment]
many thanks
