### ISSUE TITLE
Text selection not working

### ISSUE THREAD

**Issue by silverhook** [krobelus/cyanide#5]
It would be great if you could select and copy text from Cyanide (pasting works).

Currently this is not possible and (especially since links are not clickable) this is a bit annoying.

**Comment by krobelus** [comment]
I'm not sure how to do this without making the text editable - maybe there is another app that does this so I can see how it's done.

**Comment by silverhook** [comment]
The official message app e.g. has it in a way that you can at least copy the whole message, by long pressing on it.
The official mail app (and the browser, if you apply a patch) actually is able to click-drag select text for copying.

…maybe the best option would be to look at the [select text browser patch](https://github.com/CODeRUS/sailfish-browser-textselection-patch).

**Comment by krobelus** [comment]
As of 7b0ebd0a38bb06a2a88f9e69a92724364db18c9f, clicking on a message will paste it into the input field, (preceded by a '>'), so the text can be copied.
Not a great solution but at least it's not impossible now :o
