### ISSUE TITLE
Slovenian translation

### ISSUE THREAD

**Issue by silverhook** [krobelus/cyanide#8]
To make up for bothering you with bugs, I [translated the `.ts` file into Slovenian](https://thatfunkyplace.wheremymonkeyis.at/public.php?service=files&t=a11982996538ab4ea99ce2228fc43628).

I only wondered why the original `cyanide.ts` only includes two translatable entries…

**Comment by krobelus** [comment]
Thanks, I added some more strings to translate now ;)

**Comment by silverhook** [comment]
I updated the file linked about with a new translation, so you can include a fuller translation in the next version.
